"""empty message

Revision ID: 689c2960cd76
Revises: 
Create Date: 2019-06-25 16:21:08.145542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689c2960cd76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('choice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('has_choice', sa.Boolean(), nullable=True),
    sa.Column('is_multichoice', sa.Boolean(), nullable=True),
    sa.Column('has_autocomplete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field')
    op.drop_table('choice')
    # ### end Alembic commands ###
