"""empty message

Revision ID: ab2f6ca543c1
Revises: b259208de30d
Create Date: 2019-07-07 17:07:11.452467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab2f6ca543c1'
down_revision = 'b259208de30d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('field_title_has_choice_is_multichoice_has_autocomplete_key', 'field', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('field_title_has_choice_is_multichoice_has_autocomplete_key', 'field', ['title', 'has_choice', 'is_multichoice', 'has_autocomplete'])
    # ### end Alembic commands ###
